package com.reb.switchbt.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.reb.switchbt.db.DeviceBond;

import com.reb.switchbt.db.DeviceBondDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceBondDaoConfig;

    private final DeviceBondDao deviceBondDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceBondDaoConfig = daoConfigMap.get(DeviceBondDao.class).clone();
        deviceBondDaoConfig.initIdentityScope(type);

        deviceBondDao = new DeviceBondDao(deviceBondDaoConfig, this);

        registerDao(DeviceBond.class, deviceBondDao);
    }
    
    public void clear() {
        deviceBondDaoConfig.clearIdentityScope();
    }

    public DeviceBondDao getDeviceBondDao() {
        return deviceBondDao;
    }

}
